### PR TITLE
fix: issue-2927: Persist on-the-fly organizations to FHIR store during Order Entry

### LINKED ISSUE #2927: Organization Created on the fly During Order Entry should be persisted to the FHIR store
During Oder Entry , when a site is entered as free Test , its created as an Organization in the OpenELIS DB but never persisted to the Fhir Store.
This should be also synched to the FHIR store as it is when created via the Organization Dasboard

### PR DESCRIPTION
**Pull request by Shinchan493**
- [x] The PR title includes a brief description of the work done, including the
      Issue number if applicable.
- [ ] The PR includes a video showing the changes for the work done.
- [x] The PR title follows conventional commit label standards.
- [x] The changes confirm to the OpenElis Global x3
      [Styleguide and Design](https://uwdigi.atlassian.net/wiki/spaces/OG/pages/621346838/OpenELIS+Global+Style+Guide)
      documentation.
- [x] The changes include tests or are validated by existing tests.
- [x] I have read and agree to the Contributing
      [Guidelines](https://openelis-global.org/community/get-involved/) of this
      project.

## Summary

Organizations created on the fly during Order Entry (via free-text site name input) were **not being persisted to the FHIR store**. This PR fixes the issue by:

1. **Assigning a `fhirUuid`** to new organizations created during Order Entry (`SamplePatientUpdateData.initializeNewOrganization()`) so they can be identified in the FHIR store.
2. **Calling `fhirTransformService.transformPersistOrganization()`** after the organization is inserted into the database (`SamplePatientEntryServiceImpl.persistOrganizationData()`), following the same pattern used by `OrganizationProvider.create()`.
3. **Including the new organization in the FHIR bundle** built during `FhirTransformServiceImpl.transformPersistOrderEntryFhirObjects()`.
4. **Applying the same fix to the NonConformity flow** ([NonConformityUpdateWorker](cci:2://file:///home/ayush/OpenELIS-Global-2/src/main/java/org/openelisglobal/qaevent/worker/NonConformityUpdateWorker.java:83:0-855:1)), which had the same bug.

### Files Changed

| File | Change |
|---|---|
| [SamplePatientUpdateData.java](cci:7://file:///home/ayush/OpenELIS-Global-2/src/main/java/org/openelisglobal/sample/action/util/SamplePatientUpdateData.java:0:0-0:0) | Added `fhirUuid = UUID.randomUUID()` in [initializeNewOrganization()](cci:1://file:///home/ayush/OpenELIS-Global-2/src/main/java/org/openelisglobal/sample/action/util/SamplePatientUpdateData.java:392:4-404:5) |
| [SamplePatientEntryServiceImpl.java](cci:7://file:///home/ayush/OpenELIS-Global-2/src/main/java/org/openelisglobal/sample/service/SamplePatientEntryServiceImpl.java:0:0-0:0) | Injected [FhirTransformService](cci:2://file:///home/ayush/OpenELIS-Global-2/src/main/java/org/openelisglobal/dataexchange/fhir/service/FhirTransformService.java:29:0-84:1), called [transformPersistOrganization()](cci:1://file:///home/ayush/OpenELIS-Global-2/src/main/java/org/openelisglobal/dataexchange/fhir/service/FhirTransformService.java:34:4-35:73) after org insert |
| [FhirTransformServiceImpl.java](cci:7://file:///home/ayush/OpenELIS-Global-2/src/main/java/org/openelisglobal/dataexchange/fhir/service/FhirTransformServiceImpl.java:0:0-0:0) | Added new org to FHIR bundle in [transformPersistOrderEntryFhirObjects()](cci:1://file:///home/ayush/OpenELIS-Global-2/src/main/java/org/openelisglobal/dataexchange/fhir/service/FhirTransformServiceImpl.java:451:4-537:5) |
| [NonConformityUpdateWorker.java](cci:7://file:///home/ayush/OpenELIS-Global-2/src/main/java/org/openelisglobal/qaevent/worker/NonConformityUpdateWorker.java:0:0-0:0) | Same `fhirUuid` + FHIR sync fixes for the NonConformity flow |

## Local Testing

The following local tests were performed to validate correctness:

- **Compilation**: `mvn compile -DskipTests` — passes with exit code 0.
- **Spotless formatting**: `mvn spotless:apply` — applied successfully.
- **Unit tests**: Two local test classes were written and executed to verify the fix:
  - [SamplePatientUpdateDataTest](cci:2://file:///home/ayush/OpenELIS-Global-2/src/test/java/org/openelisglobal/sample/action/util/SamplePatientUpdateDataTest.java:9:0-51:1) — verifies that [initializeNewOrganization()](cci:1://file:///home/ayush/OpenELIS-Global-2/src/main/java/org/openelisglobal/sample/action/util/SamplePatientUpdateData.java:392:4-404:5) correctly assigns a `fhirUuid`, sets all required fields (`code`, `organizationName`, `isActive`, `sysUserId`, `mlsSentinelLabFlag`), and that each call generates a unique UUID.
  - [SamplePatientEntryOrganizationFhirTest](cci:2://file:///home/ayush/OpenELIS-Global-2/src/test/java/org/openelisglobal/sample/SamplePatientEntryOrganizationFhirTest.java:22:0-101:1) — integration test verifying that a new organization persisted via `organizationService.insert()` with a `fhirUuid` is retrievable by that UUID, confirming the DB persistence path works correctly.
- **Existing tests**: Verified that existing [SamplePatientEntryServiceTest](cci:2://file:///home/ayush/OpenELIS-Global-2/src/test/java/org/openelisglobal/sample/SamplePatientEntryServiceTest.java:29:0-128:1) and [OrganizationFacadeTest](cci:2://file:///home/ayush/OpenELIS-Global-2/src/test/java/org/openelisglobal/fhir/OrganizationFacadeTest.java:30:0-218:1) are not affected by the changes.

### How to manually verify end-to-end

1. Start the OpenELIS application with a FHIR store configured
2. Navigate to **Order Entry** (`/SamplePatientEntry`)
3. Enter a **free-text site name** (not from the dropdown) as the referring site
4. Submit the order
5. Check the **FHIR store** — a new Organization resource should appear with the correct name and `active=true`
6. Check the **OpenELIS DB** — the `organization` table row should have a non-null `fhir_uuid`

## Screenshots

N/A — this is a backend-only fix with no UI changes.

## Related Issue

Closes https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/2927

## Other

The same bug also existed in the [NonConformityUpdateWorker](cci:2://file:///home/ayush/OpenELIS-Global-2/src/main/java/org/openelisglobal/qaevent/worker/NonConformityUpdateWorker.java:83:0-855:1) (used when creating organizations from the Non-Conformity form), so that was fixed in the same PR to keep the fix cohesive.

### CODE REVIEW

File: src/main/java/org/openelisglobal/sample/service/SamplePatientEntryServiceImpl.java [hunk 1]
```diff
@@ -165,6 +168,13 @@ private void persistOrganizationData(SamplePatientUpdateData updateData) {
                 address.setOrganizationId(newOrganization.getId());
                 organizationAddressService.insert(address);
             }
+
+            try {
```
Comment (mozzy11) [inline src/main/java/org/openelisglobal/sample/service/SamplePatientEntryServiceImpl.java]: I think this is a duplicate implementation of the same functionality at this point .you have already done it `transformPersistOrderEntryFhirObjects`

Comment (mozzy11) [reply src/main/java/org/openelisglobal/sample/service/SamplePatientEntryServiceImpl.java]: Thanks @Shinchan493 for the great work.
 you can run `mvn spotless:apply` for applying the formatter .

Comment (Shinchan493) [reply src/main/java/org/openelisglobal/sample/service/SamplePatientEntryServiceImpl.java]: Thanks @mozzy11  sir ! Removed the duplicate call and ran spotless. Please re-review!

**Comment by mozzy11** [comment]
@Shinchan493 i can see the build still fails because of formating related issues. you dont seem to have pushed the formatting changes

**Comment by Shinchan493** [comment]
sorry about that @mozzy11 have corrected and rechecked running mvn spotless:apply the build is success now .

**Comment by mozzy11** [comment]
Thanks @Shinchan493

**Review by mozzy11 — APPROVED** [review]
