### PR TITLE
Enhance Navigation and Dashboard: Add Home Link and Interactive Tiles

### LINKED ISSUE #1399: Navigation and Dashboard Fixes: Add Home Link and Enable Tile Interactions
# Reporting an Issue with OpenELIS Global

# How to reproduce 
1. Login, you will be redirected to the home page
2. There, try clicking on tiles
3. You will not be redirected to the desired page
4. Users cannot use the side navigation bar to go to home page

# Screenshots / Screen recordings
[Screencast from 13-01-25 23:55:11.webm](https://github.com/user-attachments/assets/70bb470d-ca11-4ba1-b81f-2010ebd2f908)
Screenshot from 2025-01-13 23-56-19

The issue makes OpenELIS slow and confusing, but we are able to keep working with it.

### PR DESCRIPTION
**Pull request by harshitg927**
Fixes: [issue#1399](https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/1399)

## Summary

This pull request addresses issues related to navigation and dashboard functionality by implementing the following improvements:

1. Home Link Addition: Adds a Home link to the navigation bar for better accessibility and user experience.
2. Tile Interactions: Enables interactive functionality for dashboard tiles, allowing user to click on them to render the desired page

## Screen-recording
[Screencast from 14-01-25 23:09:08.webm](https://github.com/user-attachments/assets/e55233ce-cdb1-45f9-8365-f12c04547a5f)

## Related Issue

https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/1399

### CODE REVIEW

**Comment by harshitg927** [comment]
@Bahati308 Can you please review this pull request?

**Comment by harshitg927** [comment]
@Bahati308 One of the test cases is failing, what should I do here?

File: frontend/src/components/layout/Header.js [hunk 1]
```diff
@@ -579,6 +579,15 @@ function OEHeader(props) {
                         isPersistent={false}
                       >
                         <SideNavItems>
+                          {/* Adding the home link at the top in the side navigation bar */}
```
Comment (mozzy11) [inline frontend/src/components/layout/Header.js]: Can you discard this change here ??
we aready have a home menu item generated from the api.
I just rendered it in this PR https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/1408

Comment (harshitg927) [reply frontend/src/components/layout/Header.js]: @mozzy11 I have modified the code for the requested changes

File: frontend/src/components/home/Dashboard.tsx [hunk 2]
```diff
@@ -359,8 +359,23 @@ const HomeDashBoard: React.FC<DashBoardProps> = () => {
     }
   };
 
+  const handleTileClick = (tile) => {
```
Comment (mozzy11) [inline frontend/src/components/home/Dashboard.tsx]: By the way this function is an exact duplicate of this existing function [handleMaximizeClick](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop/frontend/src/components/home/Dashboard.tsx#L362-L377).

Why not just use an existing function instead of duplicating it ??

Comment (harshitg927) [reply frontend/src/components/home/Dashboard.tsx]: @mozzy11 I thought I should create two separate function to be called on an onClick event on different components... Anyways I will modify the code to use the existing function and push the changes... Thank You for you feedback.
