### PR TITLE
Fixed NullPointerException error

### LINKED ISSUE #2784: NullPointerException in GenderDAOImpl.duplicateGenderExists when Gender.getGenderType() returns null
During test execution of GenderServiceTest, a NullPointerException occurs in GenderDAOImpl.duplicateGenderExists at line 65. The error happens when trying to invoke String.toLowerCase() on a null value returned by Gender.getGenderType().

###  Error Logs 
```
10 Feb 2026 00:37:47 -- ERROR -- Class: org.openelisglobal.gender.daoimpl.GenderDAOImpl, 
Method: duplicateGenderExists, Line: 65, 
Message: Cannot invoke "String.toLowerCase()" because the return value of "org.openelisglobal.gender.valueholder.Gender.getGenderType()" is null
```

### Root Cause Analysis:
The method duplicateGenderExists is calling getGenderType().toLowerCase() without checking if getGenderType() returns null. This suggests either

### PR DESCRIPTION
**Pull request by Ayushdk**
Fixes #2784

### CODE REVIEW

**Comment by Ayushdk** [comment]
Hi,

The CI failures seem unrelated to my changes.

From the logs:

• Maven build is failing due to missing `dataexport-api` and `dataexport-core` dependencies.
• Submodule checkout shows a missing URL for `tools/astm-http-bridge`.
• Spotless check is also failing due to formatting issues inside the same submodule.

Since these are infra/submodule/dependency issues, could you please take a look? I can rebase or rerun CI once they’re resolved.

**Comment by Agaba-derrick** [comment]
> Hi,
> 
> The CI failures seem unrelated to my changes.
> 
> From the logs:
> 
> • Maven build is failing due to missing `dataexport-api` and `dataexport-core` dependencies. • Submodule checkout shows a missing URL for `tools/astm-http-bridge`. • Spotless check is also failing due to formatting issues inside the same submodule.
> 
> Since these are infra/submodule/dependency issues, could you please take a look? I can rebase or rerun CI once they’re resolved.

did you build before pushing this Pr ? ie  check the read  me

File: src/main/java/org/openelisglobal/gender/service/GenderServiceImpl.java [hunk 1]
```diff
@@ -24,6 +25,10 @@ protected GenderDAO getBaseObjectDAO() {
 
     @Override
     public Integer insert(Gender gender) {
+        // Validate required fields - business logic validation
+        if (gender == null || gender.getGenderType() == null || gender.getGenderType().trim().isEmpty()) {
+            throw new LIMSRuntimeException("Gender type is required and cannot be null or empty");
+        }
```
Comment (sagarkhandagre998) [inline src/main/java/org/openelisglobal/gender/service/GenderServiceImpl.java]: Create a Single Function validateGenderType(gender); and use that for following better code practises.

File: src/main/java/org/openelisglobal/gender/service/GenderServiceImpl.java [hunk 2]
```diff
@@ -32,6 +37,10 @@ public Integer insert(Gender gender) {
 
     @Override
     public Gender save(Gender gender) {
+        // Validate required fields - business logic validation
+        if (gender == null || gender.getGenderType() == null || gender.getGenderType().trim().isEmpty()) {
+            throw new LIMSRuntimeException("Gender type is required and cannot be null or empty");
+        }
```
Comment (sagarkhandagre998) [inline src/main/java/org/openelisglobal/gender/service/GenderServiceImpl.java]: same - use validateGenderType(gender);  here also

File: src/main/java/org/openelisglobal/gender/service/GenderServiceImpl.java [hunk 3]
```diff
@@ -40,6 +49,10 @@ public Gender save(Gender gender) {
 
     @Override
     public Gender update(Gender gender) {
+        // Validate required fields - business logic validation
+        if (gender == null || gender.getGenderType() == null || gender.getGenderType().trim().isEmpty()) {
+            throw new LIMSRuntimeException("Gender type is required and cannot be null or empty");
+        }
```
Comment (sagarkhandagre998) [inline src/main/java/org/openelisglobal/gender/service/GenderServiceImpl.java]: same here

File: src/main/java/org/openelisglobal/gender/daoimpl/GenderDAOImpl.java [hunk 4]
```diff
@@ -55,6 +55,10 @@ public Gender getGenderByType(String type) throws LIMSRuntimeException {
     @Override
     public boolean duplicateGenderExists(Gender gender) throws LIMSRuntimeException {
         try {
+            // Add null safety check - DAO layer should be defensive
+            if (gender == null || gender.getGenderType() == null) {
+                return false;
+            }
```
Comment (sagarkhandagre998) [inline src/main/java/org/openelisglobal/gender/daoimpl/GenderDAOImpl.java]: Why r u checking in the dao layer ?

**Review by sagarkhandagre998 — CHANGES_REQUESTED** [review]

**Comment by Ayushdk** [comment]
@sagarkhandagre998 can you review this now , please ?

i have now created a single Function validateGenderType(gender)

File: src/main/java/org/openelisglobal/gender/service/GenderServiceImpl.java [hunk 5]
```diff
@@ -23,12 +23,22 @@ protected GenderDAO getBaseObjectDAO() {
...
+     * Validates that the gender object and its genderType field are not null or
+     * empty.
+     * 
+     * @param gender the Gender object to validate
+     * @throws LIMSRuntimeException if validation fails
+     */
+    private void validateGenderType(Gender gender) {
         if (gender == null || gender.getGenderType() == null || gender.getGenderType().trim().isEmpty()) {
             throw new LIMSRuntimeException("Gender type is required and cannot be null or empty");
         }
```
Comment (sagarkhandagre998) [inline src/main/java/org/openelisglobal/gender/service/GenderServiceImpl.java]: the better option is to use StringUtil.isNullorNill()  for consistency and make sure to write the function in the last.

**Review by sagarkhandagre998 — CHANGES_REQUESTED** [review]

File: .gitmodules [hunk 6]
```diff
@@ -20,6 +20,12 @@
 	path = tools/openelis-analyzer-bridge
 	url = https://github.com/DIGI-UW/openelis-analyzer-bridge.git
 	branch = develop
+[submodule "tools/astm-http-bridge"]
+	path = tools/astm-http-bridge
+	url = https://github.com/DIGI-UW/astm-http-bridge.git
+[submodule "tools/astm-mock-server"]
+	path = tools/astm-mock-server
+	url = https://github.com/DIGI-UW/astm-mock-server.git
```
Comment (sagarkhandagre998) [inline .gitmodules]: Why did u add this ?

**Comment by Ayushdk** [comment]
@sagarkhandagre998 i changed to StringUtil.isNullorNill for the null value handling
can you please review it ?

**Review by sagarkhandagre998 — CHANGES_REQUESTED** [review]

File: .gitmodules (hunk 6 above)
Comment (Ayushdk) [reply .gitmodules]: Accidental change from initial setup , I will remove it and keep PR focused on Gender validation fix only.

**Comment by Ayushdk** [comment]
i will fix these minor mistakes,

**Comment by Ayushdk** [comment]
@sagarkhandagre998 i fixed everything now and verified 
Could you please take a look,please?

**Review by sagarkhandagre998 — APPROVED** [review]
