### PR TITLE
Fixed responsiveness in Lab Number Management

### LINKED ISSUE #1786: Improve Responsiveness for Admin Menu Configuration Pages
When you Go to the Admin Page ,
The following Conguration Pages have broken layout on smaller screen sizes 

- Dictionary Menu  ✅ 
- Lab Number Management ✅ 
- Programme Entry (✅  https://github.com/DIGI-UW/OpenELIS-Global-2/pull/1789)
- Provider Management ✅ 
-  Organization Management ✅ 
- User Management ✅ 
- Test Management > All the Rename Componenet Pages are broken

Example Provider Management Page layout breaks on small screen size

Image

Plaese for easy review , Create a separaye PR for each componeent above. 
Attach screen shots of the Layout on small , medium and large screen.
Make use of the Carbon grid layout to fix the broken responsivenes

### PR DESCRIPTION
**Pull request by Lemeri123**
# Pull Requests Requirements

- [ ] The PR title includes a brief description of the work done, including the
      Issue number if applicable.
- [ ] The PR includes a video showing the changes for the work done.
- [ ] The PR title follows conventional commit label standards.
- [ ] The changes confirm to the OpenElis Global x3 Styleguide and design
      documentation.
- [ ] The changes include tests or are validated by existing tests.
- [ ] I have read and agree to the Contributing Guidelines of this project.

## Screenshots

[Add relevant screenshots here if applicable]
Before
Screenshot from 2025-03-28 14-13-46
After
Screenshot from 2025-03-28 14-15-39

## Related Issue

[Add a link to the related issue or mention it here if applicable]
Resolves #1786
## Other

[Add any additional information or notes here]

### CODE REVIEW

File: frontend/src/components/admin/labNumber/LabNumberManagement.js [hunk 1]
```diff
@@ -177,7 +177,7 @@ function LabNumberManagement() {
         </Grid>
         <Form onSubmit={handleSubmit}>
```
Comment (adityadeshlahre) [inline frontend/src/components/admin/labNumber/LabNumberManagement.js]: just above the From Tag can you add below div TAG and close it That will add white background DEPTH on that page which is missing.

`<div className="orderLegendBody">`
