### PR TITLE
Fix rewriting test management config menu page

### LINKED ISSUE #1146: Rewrite Test Management Config Menu JSP to React JS
### URL : https://oe3.openelis-global.org/api/OpenELIS-Global/TestManagementConfigMenu

image

### PR DESCRIPTION
**Pull request by adityadeshlahre**
- referencing #1051 

- Fixes #1146 

### Converting All pages pages/sub-pages of Test Management Config Menu 

- [x] Main page (initialization done) which will render all the sub management pages 

### Spelling corrections
- [x] Rename existing test names
- [x] Rename Existing Panels
- [x] Rename Existing Test Sections
- [x] Rename Existing Unit of Measure Entries
- [x] Rename existing result list options
- [x] Rename existing method names

### Test Organization
- [x] View Test Catalog (done already) [ need to structure it ]
- [x] Manage Methods (done already) [ need to structure it ]
- [ ] Add new tests
- [ ] Modify tests
- [ ] Activate/Deactivate tests
- [ ] Enable/disable test orderability.
- [ ] Manage Test Units
- [ ] Manage Sample Types
- [ ] Manage Units of Measure
- [ ] Manage Panels
- [ ] Add result select list
- [ ] Manage Testing Algorithms and Reflex tests

## These are all the pages which are required to create eventually I will try to complete this in this PR

I will keep posting workflow of pages when it would be functional 

Thank you :slightly_smiling_face:

### CODE REVIEW

**Comment by adityadeshlahre** [comment]
### Route Page DONE (testManagementConfigPage)
`https://localhost/admin#TestRenameEntry`

#### WorkFlow VIDEO
testRenamePostRequestWorking

**Comment by adityadeshlahre** [comment]
## Panel Rename Route Done

```
https://localhost/admin#PanelRenameEntry
```

### WorkFlow Done
panelRenameEntryDone

File: frontend/src/components/admin/testManagementConfigMenu/TestManagementConfigMenu.js [hunk 1]
```diff
@@ -0,0 +1,416 @@
...
+                        <FormattedMessage id="configuration.test.add.explain" />
+                      </ListItem>
+                    </UnorderedList>
+                  </ListItem>
+                </ClickableTile>
+                <br />
+                <ClickableTile>
+                  <ListItem
+                  // onClick={() => {
+                  //   window.location.assign("/admin#TestModifyEntry");
```
Comment (mozzy11) [inline frontend/src/components/admin/testManagementConfigMenu/TestManagementConfigMenu.js]: in the case when the component doesnt exist or not functional in React , just link to the old JSP page ie `api/OpenELIS-Global/TestModifyEntry`

**Review by mozzy11 — CHANGES_REQUESTED** [review]
Thanks @adityadeshlahre .
When the on the  component on the Test management is not yet complete in the new React UI , just link to the old JSP page components

**Comment by mozzy11** [comment]
Thanks @adityadeshlahre 
Can you add a new screen recording of the new changes ??

**Comment by adityadeshlahre** [comment]
> Thanks @adityadeshlahre Can you add a new screen recording of the new changes ??

## Update Video of on click workflow

https://github.com/user-attachments/assets/ae78a075-e316-4e16-8a82-c9bb5c05d2d5

**Comment by mozzy11** [comment]
Hello @adityadeshlahre . 
Ive tried using the rename components but they dont seem to work.
Can you fix that ??

**Comment by adityadeshlahre** [comment]
> Hello @adityadeshlahre . Ive tried using the rename components but they dont seem to work. Can you fix that ??

@mozzy11 doubled checked everything is working attaching a video 


https://github.com/user-attachments/assets/8fbe866e-244b-4c95-89a3-d449694af8a8

**Review by mozzy11 — CHANGES_REQUESTED** [review]
Hello @adityadeshlahre ,
Ive tested the latest fix but its not working yet.
Can you first test your PR on a clean enviroment like gitpod ??

**Comment by mozzy11** [comment]
Hello @adityadeshlahre , thanks for the great work
