### PR TITLE
User can select date and time out correctly.

### LINKED ISSUE #1608: Fixing User Management under Home ---> Admin ---> User Management
# How to Reproduce
1. Login
2. Navigate to Admin page using the side navigation bar
3. Navigate to the User Management page

# Current Behaviour
1. While adding a new user, user is allowed to enter a previous date.
2. When the value of Is Active is N, the deactivate button disabled
3. While adding a new user, the placeholder for time out is incorrect and the user is allowed to enter negative values.

# Expected Behaviour
1. While adding a new user, the user shouldn't be allowed to enter a previous date.
2. When the value of Is Active is Y, the deactivate button should be enabled and should work as intended
3. While adding a new user, the user shouldn't be allowed to enter a negative value.
4. we need to use a Date Picker for Date input rather than free text entry

### PR DESCRIPTION
**Pull request by peach280**
# Pull Requests Requirements

- [X] The PR title includes a brief description of the work done, including the
      Issue number if applicable.
- [X] The PR includes a video showing the changes for the work done.
- [X] The PR title follows conventional commit label standards.
- [X] The changes confirm to the OpenElis Global x3 Styleguide and design
      documentation.
- [X] The changes include tests or are validated by existing tests.
- [X] I have read and agree to the Contributing Guidelines of this project.

## Summary
Fixes #1608 
In user management user can only select today's or future date and can't select negative timeout.

## Screenshots

https://github.com/user-attachments/assets/70c9097c-69ae-4eea-809e-26e9de54f644

### CODE REVIEW

File: frontend/src/components/admin/userManagement/UserAddModify.js [hunk 1]
```diff
@@ -1003,15 +1004,15 @@ function UserAddModify() {
                     </>
                   </Column>
                   <Column lg={8} md={4} sm={4}>
-                    <TextInput
+                    <input
```
Comment (mozzy11) [inline frontend/src/components/admin/userManagement/UserAddModify.js]: We are strictly using Carbon components , not the default html componenets

File: frontend/src/components/admin/userManagement/UserAddModify.js [hunk 2]
```diff
@@ -1031,15 +1033,15 @@ function UserAddModify() {
...
```
Comment (mozzy11) [inline frontend/src/components/admin/userManagement/UserAddModify.js]: we are using Carbon as a Style Guide so we dont encourage using the default html components

**Comment by mozzy11** [comment]
Thanks @peach280 . This seems to no work as it create a wrong date format. Can you use the existing [CustomDatePicker](https://github.com/DIGI-UW/OpenELIS-Global-2/blob/63af2c1d12cec6ba8a261c7e6bfe354b837f4064/frontend/src/components/common/CustomDatePicker.js)

**Comment by peach280** [comment]
Hi @mozzy11 , I have made the changes to use CustomDatePicker and using carbon components. Please review.

https://github.com/user-attachments/assets/9eecb10c-47ad-4af7-82b7-dfd3dee78813

**Comment by mozzy11** [comment]
@peach280 have tested with rendering an existing user?
have you also tried adding a new user and see if that works fine?

**Comment by peach280** [comment]
Yes @mozzy11 I have tested. This is the video.

https://github.com/user-attachments/assets/fdf219e6-232d-4171-89cc-43d8013b3118

**Comment by mozzy11** [comment]
Thanks @peach280 . Can you create a full video Adding the User and Viewing the user on the modify page to ensure the component can display the entered date correctly ??
