### PR TITLE
Scroll and Dropdown features are now responsive for Provider Management and Analyzer test name pages.

### LINKED ISSUE #1410: Scroll and Dropdown features not responsive
# Scroll and Dropdown features not responsive

1. Ways to reproduce:
  Admin -----> Analyzer Test Name ---> add button
Admin -----> Provider Management ---> add button
3. The scroll  dreop-down features are not working as intended

4. URLs 
  https://localhost/MasterListsPage#providerMenu  
https://localhost/MasterListsPage#AnalyzerTestName

5. Screenshots 
[Screencast from 2025-01-16 12-14-43.webm](https://github.com/user-attachments/assets/fe70f354-26bf-4446-868b-d171b8f43e70)
and video recordings .

6. Indicate the severity of the issue using the following ratings:
   1. This issue makes OpenELIS slow, difficult, or confusing, but we are able
      to keep working with it.
   3. This issue prevents us from using OpenELIS effectively

### PR DESCRIPTION
**Pull request by peach280**
# Pull Requests Requirements

- [X] The PR title includes a brief description of the work done, including the
      Issue number if applicable.
- [X] The PR includes a video showing the changes for the work done.
- [X] The PR title follows conventional commit label standards.
- [X] The changes confirm to the OpenElis Global x3 Styleguide and design
      documentation.

## Summary

Fixes #1410 
The Provider Management page and Analyzer test page have been made responsive with the dropdown menu.

https://github.com/user-attachments/assets/a28c95f1-6265-41aa-91f1-5225ce6e0bca

### CODE REVIEW

**Comment by peach280** [comment]
Hi, I have a small query. Every time I generate a pull request, even after I resolve the conflicts, github says my branch is out of date and as soon as I update my branch it starts running tests again? So should I not update my branch every time I open a PR?

**Comment by mozzy11** [comment]
can you run the formatter to format you code ??

File: frontend/src/components/admin/ProviderMenu/ProviderMenu.js [hunk 1]
```diff
@@ -403,13 +403,8 @@ function ProviderMenu() {
             value={telephone}
             onChange={(e) => setTelephone(e.target.value)}
           />
-          <TextInput
```
Comment (mozzy11) [inline frontend/src/components/admin/ProviderMenu/ProviderMenu.js:454]: any reason you shifted this field below ??

File: frontend/src/components/admin/analyzerTestName/AnalyzerTestName.js [hunk 2]
```diff
@@ -369,18 +369,6 @@ function AnalyzerTestName() {
               setSelectedAnalyzerId(selectedItem ? selectedItem.id : null);
             }}
           />
-          <br />
-          <TextInput
```
Comment (mozzy11) [inline frontend/src/components/admin/analyzerTestName/AnalyzerTestName.js:373]: any reason you shifted the field ??

File: frontend/src/components/admin/ProviderMenu/ProviderMenu.js (hunk 1 above)
Comment (peach280) [reply frontend/src/components/admin/ProviderMenu/ProviderMenu.js:454]: Actually according to this issue #1410  the user was not able to see the options in dropdown menu as it wasn't auto scrolling. So I shifted the dropdown above so that user can see without scrolling.

File: frontend/src/components/admin/analyzerTestName/AnalyzerTestName.js (hunk 2 above)
Comment (peach280) [reply frontend/src/components/admin/analyzerTestName/AnalyzerTestName.js:373]: In this dropdown when expanded wasn't visible so I shifted it above.

**Comment by peach280** [comment]
> can you run the formatter to format you code ??

I ran the formatter still failing.

**Comment by peach280** [comment]
Hi @mozzy11 I have made the design responsive by shifting dropdown menu above but I had one query.

Untitled


The first dropdown menu in Analyzer Test Name called Analyzer, is displaying contents of analyzerlist and I logged it in console and this list is empty that's why the dropdown is empty. To populate this list there is an api call being made the address of which I can't find in the codebase. Your guidance will really help me in solving this issue.

**Comment by mozzy11** [comment]
Fix the formatting issues , but also do the same for the Update Models too and attach a screen recording for both the Add and Update models

**Comment by peach280** [comment]
Ok I will surely do that, but what about the first analyser whose drop-down is empty, as mentioned here [https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/1467#issuecomment-2652606250](https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/1467#issuecomment-2652606250)

**Comment by peach280** [comment]
https://github.com/user-attachments/assets/3f6174df-5fe6-4340-b351-b440fd31e084

Made the dropdown responsive for provider management. Screen Recording attached.

**Comment by mozzy11** [comment]
@peach280 can you fix the merge conflicts here ?
